# Generated by Django 5.2.11 on 2026-05-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealslot',
            unique_together={('hostel', 'day', 'slot')},
        ),
    ]
