# Generated by Django 5.2.11 on 2026-05-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mealslot_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealslot',
            name='date',
        ),
    ]
