# Generated by Django 5.2.11 on 2026-05-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_mealslot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='slot_timings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
