# Generated by Django 5.2.13 on 2026-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='booking_cutoff_time',
            field=models.TimeField(default='17:00:00'),
        ),
    ]
