# Generated by Django 5.2.13 on 2026-05-15 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmeal',
            name='is_late_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingmeal',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookingmeal',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('consumed', 'Consumed'), ('expired', 'Expired')], default='booked', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.booking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.item')),
                ('meal_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_bookings', to='api.mealslot')),
            ],
            options={
                'verbose_name_plural': 'Booking Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combos', models.ManyToManyField(related_name='daily_menus', to='api.combo')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='api.hostel')),
                ('items', models.ManyToManyField(blank=True, related_name='daily_menus', to='api.item')),
            ],
            options={
                'verbose_name_plural': 'Daily Menus',
                'ordering': ['date', 'slot'],
                'unique_together': {('hostel', 'date', 'slot')},
            },
        ),
    ]
