# Generated by Django 5.2.13 on 2026-05-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bookingmeal_is_late_booking_bookingmeal_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingmeal',
            unique_together={('booking', 'meal_slot', 'combo')},
        ),
    ]
