# Generated by Django 5.2.13 on 2026-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_bookingmeal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealslot',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='meal_slots', to='api.item'),
        ),
    ]
