# Generated by Django 5.2.13 on 2026-05-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_mealslot_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmeal',
            name='selected_items',
            field=models.ManyToManyField(blank=True, to='api.item'),
        ),
    ]
