# Generated by Django 5.2.13 on 2026-05-16 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_bookingmeal_selected_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='category',
        ),
    ]
