# Generated by Django 5.2.13 on 2026-05-16 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_combo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='api.bookingmeal')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
        ),
    ]
