# Generated by Django 5.2.11 on 2026-05-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_bookingmealitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='cancellation_cutoff_time',
            field=models.TimeField(default='16:00:00', help_text='Time two days prior after which cancellation closes'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='late_booking_lead_time_hours',
            field=models.PositiveIntegerField(default=2, help_text="Hours before meal slot during which today's booking is allowed"),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='booking_cutoff_time',
            field=models.TimeField(default='14:00:00', help_text='Time two days prior after which regular booking closes'),
        ),
    ]
