# Generated by Django 5.2.13 on 2026-05-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_institutionalevent_alter_feedback_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alloweduser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff')], default='student', max_length=20),
        ),
    ]
