# Generated by Django 5.2.13 on 2026-05-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alloweduser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpass',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='eventpass',
            name='meal_slots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
