# Generated by Django 5.2.13 on 2026-05-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_eventpass_email_eventpass_meal_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='excluded_for_faculty',
            field=models.BooleanField(default=False, help_text='If true, faculty cannot book in this hostel'),
        ),
    ]
